#!/bin/bash
#
# List all mapping dependencies for all mappings

function usage () {
    echo "$(basename "$0") DEVICE"
    exit 2
}

DEVICE="$1"
[ -z "${DEVICE}" ] && usage

while IFS=':' read fcmapid fcmapname sourceid sourcename destid destname grpid grpname trash; do
    [ "${fcmapid}" = "id" ] && continue
    depends=$(ssh -n ${DEVICE} lsfcmapdependentmaps ${fcmapid})
    if [ -n "${depends}" ]; then
        echo -e "\n==== ${fcmapid}: ${fcmapname} (${sourcename} => ${destname}) ====\n${depends}"
    else
        echo -n "." >&2
    fi
done < <(ssh ${DEVICE} lsfcmap -delim :)
