#!/bin/bash
#
# Description: Get vDisk and mapping information for history
# Author:      Christophe Drevet-Droguet

typeset PROG="$(basename "$0")"
typeset VERSION="0.2"

function usage () {
    echo "${PROG} version ${VERSION}"
    echo "usage: ${PROG} DEVICE GITREPO"
    echo ""
    echo "  PARAMETERS:"
    echo "    DEVICE:  Hostname of the storage cluster"
    echo "    GITREPO: git repository working dir"
    if [ "$#" != "0" ]; then
        echo -e "\n$@" >&2
    fi
    exit 2
}

function error {
    echo "$@" >&2
    exit 1
}

typeset _dev=
typeset _gitrepo=
typeset imax="$#"

for (( i=0; i<${imax}; i++ )); do
    if [ -z "${_dev}" ]; then
        _dev="$1"
    elif [ -z "${_gitrepo}" ]; then
        _gitrepo="$1"
    fi
    shift
done

[ -z "${_dev}" -o -z "${_gitrepo}" ] && usage

[ ! -d "${_gitrepo}/.git" ] && usage "ERROR: inexistent git repository '${_gitrepo}'"

cd "${_gitrepo}" || error "ERROR: can't change to directory ${_gitrepo}"
git reset --hard
git pull
ssh -n "${_dev}" "lsvdisk -delim ';'"        > vdisk.list
ssh -n "${_dev}" "lshostvdiskmap -delim ';'" > hostvdiskmap.list
ssh -n "${_dev}" "lsfcmap -delim ';'"        > fcmap.list
ssh -n "${_dev}" "lsfcconsistgrp -delim ';'" > fcconsistgrp.list
git add -A .
git commit -m "automatic update"
git push --force
