#!/bin/bash
#
# List all FlashCopy mappings parameters
PROG="$(basename "$0")"
VERSION="dev"

function usage () {
    echo "Version: ${VERSION}"
    echo "${PROG} DEVICE"
    exit 2
}

DEVICE="$1"
[ -z "${DEVICE}" ] && usage

echo -n "id:name:source_vdisk_id:source_vdisk_name:target_vdisk_id:"
echo -n "target_vdisk_name:group_id:group_name:status:progress:copy_rate:"
echo -n "start_time:dependent_mappings:autodelete:clean_progress:clean_rate:"
echo -n "incremental:difference:grain_size:IO_group_id:IO_group_name:"
echo    "partner_FC_id:partner_FC_name:restoring:rc_controlled"
while IFS=':' read id trash; do
    while IFS=':' read param value; do
        echo -n "${value}"
	[ "${id}" != "rc_controlled" ] && echo -n ":"
    done < <(ssh -n ${DEVICE} "lsfcmap -delim : ${id}")
    echo ""
done < <(ssh ${DEVICE} lsfcmap -nohdr -delim :)
echo ""
