#!/bin/bash
#
# Description: vDisk - Host mapping
# Author:      Christophe Drevet-Droguet

typeset PROG="$(basename "$0")"
typeset VERSION="dev"

typeset _host
typeset _dev="$1"
typeset _hosts="$2"
typeset _vdisk="$3"
typeset _scsiid="$4"

if [ -z "${_dev}" -o -z "${_hosts}" -o -z "${_vdisk}" ]; then
    echo "${PROG} version ${VERSION}"
    echo "usage: ${PROG} DEVICE HOSTS_PATTERN VDISK_NAME [SCSI_ID]"
    exit 2
fi

typeset _f1 _f2 _id _f4
typeset _maxid=0

# Check SCSI ID in use, and get the next available
while read _f1 _f2 _id _f4; do
    [ "${_f1}" = "id" ] && continue
    if [ "${_id}" = "${_scsiid}" ]; then
        echo "ERROR: SCSI ID already in use: ${_scsiid}"
        exit 1
    fi
    [ "${_id}" -ge "${_maxid}" ] && _maxid=$((_maxid + 1))
done < <(ssh -n "${_dev}" lshostvdiskmap)

typeset _scsi
if [ -z "${_scsiid}" ]; then
    echo "INFO: Using ${_maxid} as SCSI ID"
    _scsi="-scsi ${_maxid}"
else
    _scsi="-scsi ${_scsiid}"
fi

while read _host; do
    echo -n "${_host}: "
    ssh -n "${_dev}" mkvdiskhostmap -force -host ${_host} ${_scsi} ${_vdisk}
done < <(ssh "${_dev}" lshost -delim : | cut -d: -f2 | grep "${_hosts}")
